### ISSUE TITLE
bug: build images manage.sh build-bundle error

### ISSUE THREAD

**Issue by VVege** [uxbox/uxbox#3058]
### Steps To Reproduce

1. change some code
2. call ./manage.sh build-bundle
3. Terminal stuck and does not continue

### Expected behavior

it can build-bundle success .and then I can call ./manage.sh build-docker-images。to generage docker images. 

### Actual behavior

when I call ./manage.sh build-bundle。Terminal stuck and does not continue
error
`[:main] Compiling ...
Failed reading cache for app.main.data.workspace.path.shapes-to-path: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (FileInputStream); line: 1, column: 210004])
 at [Source: (FileInputStream); line: 1, column: 210012]
Failed reading cache for app.main.data.workspace.modifiers: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (FileInputStream); line: 1, column: 184873])
 at [Source: (FileInputStream); line: 1, column: 184884]
Failed reading cache for app.util.text-editor: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (FileInputStream); line: 1, column: 108844])
 at [Source: (FileInputStream); line: 1, column: 108850]
Failed reading cache for app.main.data.workspace.texts: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (FileInputStream); line: 1, column: 209895])
 at [Source: (FileInputStream); line: 1, column: 210024]
Failed reading cache for app.main.data.workspace.colors: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (FileInputStream); line: 1, column: 217080])
 at [Source: (FileInputStream); line: 1, column: 217129]
Failed reading cache for app.main.data.workspace.shape-layout: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: (FileInputStream); line: 1, column: 110363])
 at [Source: (FileInputStream); line: 1, column: 110371]`
 

### Environment (please complete the following information)

MacOS Big Sur 11.7.2
Docker: 20.10.23
Docker Compose 2.15.1
penpot git tag : 1.17.2

**Comment by VVege** [comment]
I want to generate new docker images after modifying the code, is my process correct?
1: ./manage.sh build-bundle
2. ./manage.sh build-docker-images
Or is there another way?

**Comment by VVege** [comment]
I don't know if this error is normal? Will the Terminal task continue? The terminal task doesn't exit, it just gets stuck there。

**Comment by niwinz** [comment]
I'm not clearly understand the error, the trace looks a bit limited, I mean I can't see the real cause of it.
And yes, the steps are correct, and we are running continuous build and deploy ourselves so it should work.

**Comment by VVege** [comment]
Thank you for your response. Every time I run ./manage.sh build-bundle, it runs very slowly and gets stuck at one step. I haven't been able to complete it successfully yet. How long does it usually take for you to run it?

----
this time it stuck ‘clojure -T:build jar’ for 30 minutes。
-----
whole logs：
```
> 

kwai@kwaideMacBook-Pro penpot % ./manage.sh build-bundle
+ case $1 in
+ build-frontend-bundle
+ echo '>> bundle frontend start'
>> bundle frontend start
+ mkdir -p ./bundles
++ print-current-version
++ echo -n 1.17.2-9408-g24fa4f71a
+ local version=1.17.2-9408-g24fa4f71a
+ local bundle_dir=./bundles/frontend
+ build frontend
+ echo '>> build start: frontend'
>> build start: frontend
++ print-current-version
++ echo -n 1.17.2-9408-g24fa4f71a
+ local version=1.17.2-9408-g24fa4f71a
+ pull-devenv-if-not-exists
++ docker images penpotapp/devenv:latest -q
+ [[ ! -n 8a19eef72553 ]]
+ docker volume create penpotdev_user_data
penpotdev_user_data
++ pwd
+ docker run -t --rm --mount source=penpotdev_user_data,type=volume,target=/home/penpot/ --mount source=/Users/kwai/Desktop/github/penpot,type=bind,target=/home/penpot/penpot -e EXTERNAL_UID=501 -e SHADOWCLJS_EXTRA_PARAMS= -w /home/penpot/penpot/frontend penpotapp/devenv:latest sudo -EH -u penpot ./scripts/build 1.17.2-9408-g24fa4f71a
+ CURRENT_VERSION=1.17.2-9408-g24fa4f71a
++ date -R
+ BUILD_DATE='Mon, 20 Mar 2023 10:43:46 +0000'
++ git rev-parse --short HEAD
+ CURRENT_HASH=24fa4f71a
+ EXTRA_PARAMS=
+ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.41s.
+ npx gulp clean
[10:43:55] Using gulpfile ~/penpot/frontend/gulpfile.js
[10:43:55] Starting 'clean'...
[10:43:56] Finished 'clean' after 481 ms
+ clojure -J-Xms100M -J-Xmx800M -J-XX:+UseSerialGC -M:dev:shadow-cljs release main --config-merge '{:release-version "24fa4f71a"}'
[:main] Compiling ...
[:main] Build completed. (1714 files, 0 compiled, 0 warnings, 97.97s)
+ npx gulp build
[10:46:11] Using gulpfile ~/penpot/frontend/gulpfile.js
[10:46:11] Starting 'build'...
[10:46:11] Starting 'polyfills'...
[10:46:11] Starting 'scss'...
[10:46:11] Starting 'templates'...
[10:46:11] Starting 'copy:assets'...
[10:46:11] Starting 'svg:sprite:icons'...
[10:46:11] Starting 'copy:assets:images'...
[10:46:11] Starting 'copy:assets:fonts'...
[10:46:14] gulp-postcss: main-default.css
autoprefixer: /home/penpot/penpot/frontend/resources/styles/main-default.css:11454:3: start value has mixed support, consider using flex-start instead
autoprefixer: /home/penpot/penpot/frontend/resources/styles/main-default.css:13196:3: start value has mixed support, consider using flex-start instead
autoprefixer: /home/penpot/penpot/frontend/resources/styles/main-default.css:13202:3: start value has mixed support, consider using flex-start instead
autoprefixer: /home/penpot/penpot/frontend/resources/styles/main-default.css:14317:3: start value has mixed support, consider using flex-start instead
autoprefixer: /home/penpot/penpot/frontend/resources/styles/main-default.css:15097:3: start value has mixed support, consider using flex-start instead
autoprefixer: /home/penpot/penpot/frontend/resources/styles/main-default.css:15792:3: end value has mixed support, consider using flex-end instead
[10:46:14] Finished 'scss' after 2.81 s
[10:46:14] Finished 'polyfills' after 2.84 s
[10:46:16] Finished 'copy:assets:fonts' after 4.98 s
[10:46:17] Finished 'svg:sprite:icons' after 5.44 s
[10:46:17] Starting 'svg:sprite:cursors'...
[10:46:17] Finished 'svg:sprite:cursors' after 205 ms
[10:46:17] Starting 'template:main'...
[10:46:17] Finished 'template:main' after 572 ms
[10:46:17] Starting 'template:render'...
[10:46:18] Finished 'template:render' after 339 ms
[10:46:18] Finished 'templates' after 6.57 s
[10:46:19] Finished 'copy:assets:images' after 7.83 s
[10:46:19] Finished 'copy:assets' after 7.84 s
[10:46:19] Finished 'build' after 7.85 s
+ npx gulp dist:clean
[10:46:25] Using gulpfile ~/penpot/frontend/gulpfile.js
[10:46:25] Starting 'dist:clean'...
[10:46:25] Finished 'dist:clean' after 6.87 ms
+ npx gulp dist:copy
[10:46:30] Using gulpfile ~/penpot/frontend/gulpfile.js
[10:46:30] Starting 'dist:copy'...
[10:46:34] Finished 'dist:copy' after 3.65 s
+ sed -i -re 's/\%version\%/1.17.2-9408-g24fa4f71a/g' ./target/dist/index.html
+ sed -i -re 's/\%buildDate\%/Mon, 20 Mar 2023 10:43:46 +0000/g' ./target/dist/index.html
+ echo '>> build end: frontend'
>> build end: frontend
+ rm -rf ./bundles/frontend
+ mv ./frontend/target/dist ./bundles/frontend
+ echo 1.17.2-9408-g24fa4f71a
+ put-license-file ./bundles/frontend
+ local target=./bundles/frontend
+ tee -a ./bundles/frontend/LICENSE
+ echo '>> bundle frontend end'
>> bundle frontend end
+ build-backend-bundle
+ echo '>> bundle backend start'
>> bundle backend start
+ mkdir -p ./bundles
++ print-current-version
++ echo -n 1.17.2-9408-g24fa4f71a
+ local version=1.17.2-9408-g24fa4f71a
+ local bundle_dir=./bundles/backend
+ build backend
+ echo '>> build start: backend'
>> build start: backend
++ print-current-version
++ echo -n 1.17.2-9408-g24fa4f71a
+ local version=1.17.2-9408-g24fa4f71a
+ pull-devenv-if-not-exists
++ docker images penpotapp/devenv:latest -q
+ [[ ! -n 8a19eef72553 ]]
+ docker volume create penpotdev_user_data
penpotdev_user_data
++ pwd
+ docker run -t --rm --mount source=penpotdev_user_data,type=volume,target=/home/penpot/ --mount source=/Users/kwai/Desktop/github/penpot,type=bind,target=/home/penpot/penpot -e EXTERNAL_UID=501 -e SHADOWCLJS_EXTRA_PARAMS= -w /home/penpot/penpot/backend penpotapp/devenv:latest sudo -EH -u penpot ./scripts/build 1.17.2-9408-g24fa4f71a
+ rm -rf target
+ mkdir -p target/classes
+ mkdir -p target/dist
+ echo 1.17.2-9408-g24fa4f71a
+ cp ../CHANGES.md target/classes/changelog.md
+ clojure -T:build jar
```

**Comment by niwinz** [comment]
it should take +- 5 min for complete the bundle, the docker images build I don't know, let me try it right now

**Comment by VVege** [comment]
👌 I tried twice again, and both times got stuck at the step of 'clojure -T:build jar'. It's really frustrating.😢

> it should take +- 5 min for complete the bundle, the docker images build I don't know, let me try it right now

**Comment by niwinz** [comment]
Maybe is a network problem?, try to execute `clojure -X:deps prep` in the `<repo-dir>/backend` directory, if it stuck, this means that the command is unable to download dependencies for some reason...

**Comment by VVege** [comment]
I can run `clojure -X:deps prep` success，it download many libs。but run `./manage.sh build-bundle` Again，it still stuck at `clojure -T:build jar`

**Comment by niwinz** [comment]
Ok, lets debug the jar build step, please open on your editor the `backend/build.clj` file...
And replace the `jar` function with the following code:

```clojure
(defn jar [_]
  (prn "step 1")
  (b/copy-dir
   {:src-dirs ["src" "resources"]
    :target-dir class-dir})

  (prn "step 2")

  (b/uber
   {:class-dir class-dir
    :uber-file jar-file
    :main 'clojure.main
    :exclude [#".*Log4j2Plugins\.dat$"]
    :basis basis})

  (prn "end"))
```

Then, staying on the backend directory, execute `clojure -T:build jar`

**Comment by VVege** [comment]
`Then, staying on the backend directory, execute clojure -T:build jar`
after changing the code，I can pass all step successfully on the backend directory。

and I find this code is different from the source code，I also add step logs in source code，like this

> 
(defn jar [_]
  (b/copy-dir
   {:src-dirs ["src" "resources"]
    :target-dir class-dir})
  (prn "step 1")
  (b/compile-clj
   {:basis basis
    :src-dirs ["src"]
    :class-dir class-dir})
  (prn "step 2")
  (b/uber
   {:class-dir class-dir
    :uber-file jar-file
    :main 'clojure.main
    :exclude [#"goog.*" #"^javasist.*"]
    :basis basis})
  (prn "end"))
  

> 

  I can still successfully output all the logs on the backend directory。

but when I run `./manage.sh build-bundle`，it still stuck on `clojure -T:build jar`。and this time the log is only step1，step2.
no ‘end’ output。。。

Is there any issue with running this code on Docker?

> (b/uber
   {:class-dir class-dir
    :uber-file jar-file
    :main 'clojure.main
    :exclude [#"goog.*" #"^javasist.*"]
    :basis basis})


Or this docker command is causing performance bottleneck in Docker？my Mac's fan is constantly running.

> 
docker run -t --rm --mount source=penpotdev_user_data,type=volume,target=/home/penpot/ --mount source=/Users/kwai/Desktop/github/penpot,type=bind,target=/home/penpot/penpot -e EXTERNAL_UID=501 -e SHADOWCLJS_EXTRA_PARAMS= -w /home/penpot/penpot/backend penpotapp/devenv:latest sudo -EH -u penpot ./scripts/build 1.17.2-9408-g24fa4f71a

**Comment by niwinz** [comment]
running it on docker when the host is a Mac can be a real performance problem.
On difference with running docker on linux, is that communication layer (the filesystem) access from docker to host is transparent and high performant, but docker on mac starts a virtul machine where the docker containers run and the filesystem communication from docker to mac becomes a problem and big bottleneck. In other words the filesystem layer used on docker mac for communicate host (Mac) with docker is very very slow and can be probably a cause of all this issues.
Docker on mac is just a hack for make work docker on mac, but it less than ideal for normal workloads. This will probably will run more quickly if you run it directly on Mac (but there I can't help you because I don't use and don't have mac for it).

**Comment by VVege** [comment]
Sure, thank you. It seems like I need to explore how to use server build.
Although I know it runs the two steps of "1. ./manage.sh build-bundle" and "2. ./manage.sh build-docker-images", I still have some questions，So could you explain how you generated and published the image?

> 
First I check the travis.yml

script:
  - ./manage.sh build-devenv
  - ./manage.sh run-frontend-tests
  - ./manage.sh run-backend-tests
  - ./manage.sh build-images
  - ./manage.sh run
  
  What is the purpose of this process？and I could not find  run-frontend-tests、 build-images、run in ./manage.sh why？

> 

Second。 `docker/images/build.sh`What does this script do? I couldn't find any references to this script.

**Comment by niwinz** [comment]
travis.yml is outdated and we are not using it.

The process for generate images is just that:

Build bundle: consists on generating the artifacts (production builds of each module).
```
./manage.sh build-bundle
```

This will generate `<repo-root>/backend/bundles` directory with the artifacts.

Then, we need to generate docker images, here you have the simple option, for generate a simple image based on the current bundle:

```
./manage.sh build-docker-images
```

There is also `<repo-root>/docker/images/build.sh` is a helper for create multiplatform images (images that run on x86 and arm) but you don't need this because this is just for pushing them to the registry because you can't use the generated images directly (they are not imported to the local docker instance)

For build all images on the host machine you should have openjdk >=17 and nodejs last LTS properly setup

**Comment by VVege** [comment]
ok，now， I get a centos server，but when execute `./manage.sh build-bundle` it errors when build frontend

> 

[4/4] Building fresh packages...
Done in 79.49s.
+ npx gulp clean
[02:27:49] Using gulpfile ~/penpot/frontend/gulpfile.js
[02:27:49] Starting 'clean'...
[02:27:49] Finished 'clean' after 4.44 ms
+ clojure -J-Xms100M -J-Xmx800M -J-XX:+UseSerialGC -M:dev:shadow-cljs release main --config-merge '{:release-version "ce3e30ea0"}'
Downloading: org/clojure/tools.namespace/maven-metadata.xml from central
Error building classpath. Failed to resolve version for binaryage:devtools:jar:RELEASE: Could not find metadata binaryage:devtools/maven-metadata.xml in local (/home/penpot/.m2/repository)
org.eclipse.aether.resolution.VersionResolutionException: Failed to resolve version for binaryage:devtools:jar:RELEASE: Could not find metadata binaryage:devtools/maven-metadata.xml in local (/home/penpot/.m2/repository)
	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:276)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveVersion(DefaultRepositorySystem.java:244)
	at clojure.tools.deps.extensions.maven$fn__1097.invokeStatic(maven.clj:70)
	at clojure.tools.deps.extensions.maven$fn__1097.invoke(maven.clj:59)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at clojure.tools.deps$canonicalize_deps$fn__749.invoke(deps.clj:365)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.tools.deps$canonicalize_deps.invokeStatic(deps.clj:362)
	at clojure.tools.deps$resolve_deps.invokeStatic(deps.clj:494)
	at clojure.tools.deps$calc_basis.invokeStatic(deps.clj:750)
	at clojure.tools.deps.script.make_classpath2$run_core.invokeStatic(make_classpath2.clj:111)
	at clojure.tools.deps.script.make_classpath2$run.invokeStatic(make_classpath2.clj:153)
	at clojure.tools.deps.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:203)
	at clojure.tools.deps.script.make_classpath2$_main.doInvoke(make_classpath2.clj:174)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Caused by: org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata binaryage:devtools/maven-metadata.xml in local (/home/penpot/.m2/repository)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:222)
	at org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:183)
	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:213)
	... 27 more
+ exit 1

> 

I check the deps.edn in frontend

> 

binaryage/devtools {:mvn/version "RELEASE"}
>
Is there any problem with the way "release" is written?

**Comment by niwinz** [comment]
There should be no problem, as I indicated, these operations are constantly executed in a CI and the continuous deploy.
Which JDK you have installed?
Do you have correct ssl certificates setup on your system. On debian sistem it requires installing `ca-certificates` but I don't know the equivalent on centos. Maybe:

```
yum install -y ca-certificates
```

if the previous does not works, you can try to download the *tar.gz* from https://adoptium.net/temurin/releases/?version=19, extract on the home (per example in `jdk` directory), and then:

```bash
export PATH="/home/penpot/jdk/bin:$PATH"
export JAVA_HOME="/home/penpot/jdk"
cd penpot/backend;
./manage.sh build-bundle
```

**Comment by VVege** [comment]
I have a question: Do I need to manually install JDK? My understanding is that when I call "./manage.sh buildbundles", it will start the devenv container and complete the build inside the container. Therefore, I shouldn't need to manually install JDK, right?

**Comment by VVege** [comment]
I have another question, thank you for the reply. If I only want to modify the frontend code, can I generate a separate image for the frontend and deploy it on a new server? Can the backend and exporter use the docker-compose.yaml from the official website directly? Is it feasible to have the frontend and backend on different servers? What specific configurations are needed?

**Comment by niwinz** [comment]
> I have a question: Do I need to manually install JDK? My understanding is that when I call "./manage.sh buildbundles", it will start the devenv container and complete the build inside the container. Therefore, I shouldn't need to manually install JDK, right?

Hmm, you are completly right, this should run the build process in the docker so, no JDK on the system is involved, sorry for the confusion; for some reason I though you trying to build it on the host... 
So still don't undertand the issue then :( something docker/network related maybe? :S )

**Comment by niwinz** [comment]
> I have another question, thank you for the reply. If I only want to modify the frontend code, can I generate a separate image for the frontend and deploy it on a new server? Can the backend and exporter use the docker-compose.yaml from the official website directly? Is it feasible to have the frontend and backend on different servers? What specific configurations are needed?

Yep, it is possible to run the containers on different servers, but frontend container need to know how to acces to the backend and exporter and requires `PENPOT_BACKEND_URI` and `PENPOT_EXPORTER_URI` environment variables set to a proper URIS

**Comment by VVege** [comment]
> 

thanks，but I check the docker-compose.yaml, it can find 

> 
penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: always
    networks:
      - penpot

    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend

      ## Redis is used for the websockets notifications.
      - PENPOT_REDIS_URI=redis://penpot-redis/0

> 
 penpot-exporter has environment `PENPOT_PUBLIC_URI=http://penpot-frontend` . if My frontend in the other server, Will it affect the communication between the exporter and the frontend? And he commented, "don't touch it"

**Comment by VVege** [comment]
did i set the config right?

> 
`var PENPOT_BACKEND_URI='http://my-penpot-backend';`
`var PENPOT_EXPORTER_URI='http://my-penpot-exporter';`
> 

put this in frontend/resources/public/js/config.js. ?

this docment https://help.penpot.app/technical-guide/developer/common/#dev-environment  says in that file. but no say how to write in config.js

**Comment by niwinz** [comment]
> > 
> 
> thanks，but I check the docker-compose.yaml, it can find
> 
> > 
> 
> penpot-exporter: image: "penpotapp/exporter:latest" restart: always networks: - penpot
> 
> ```
> environment:
>   # Don't touch it; this uses internal docker network to
>   # communicate with the frontend.
>   - PENPOT_PUBLIC_URI=http://penpot-frontend
> 
>   ## Redis is used for the websockets notifications.
>   - PENPOT_REDIS_URI=redis://penpot-redis/0
> ```
> 
> > 
> 
> penpot-exporter has environment `PENPOT_PUBLIC_URI=http://penpot-frontend` . if My frontend in the other server, Will it affect the communication between the exporter and the frontend? And he commented, "don't touch it"

Yep, the exporter also need access to the frontend, it says do not touch it inside the docker compose environment, but if you setup it on your own, you will need to adjust it.

**Comment by niwinz** [comment]
> did i set the config right?
> 
> > 
> 
> `var PENPOT_BACKEND_URI='http://my-penpot-backend';` `var PENPOT_EXPORTER_URI='http://my-penpot-exporter';`
> 
> > 
> 
> put this in frontend/resources/public/js/config.js. ?
> 
> this docment https://help.penpot.app/technical-guide/developer/common/#dev-environment says in that file. but no say how to write in config.js

Hmm, that are environment variables and not js variables.
This environment variables are read by the frontend docker image entrypoint script and generates proper nginx.conf [(look here)](https://github.com/penpot/penpot/blob/develop/docker/images/files/nginx-entrypoint.sh#L25)
