### ISSUE TITLE
bug: Email functionality broken in version 1.18.1

### ISSUE THREAD

**Issue by BlessedDisco** [uxbox/uxbox#3112]
I have configured Postmark as an SMTP-server for penpot to send emails, like invitations.

After upgrading to penpot 1.18.1, Postmark complains that the received emails are invalid: `ErrorCode: '300', Message: 'Invalid 'From' value.'`. When I downgrade the docker containers to version 1.17.1 or 1.18.0, the email functionality works again.

I use the following SMTP configuration:
```
      - PENPOT_SMTP_DEFAULT_FROM=noreply@domain.dev
      - PENPOT_SMTP_DEFAULT_REPLY_TO=noreply@domain.dev
      - PENPOT_SMTP_HOST=smtp.postmarkapp.com
      - PENPOT_SMTP_PORT=587
      - PENPOT_SMTP_USERNAME=SOME_USERNAME
      - PENPOT_SMTP_PASSWORD=SOME_PASSWORD
      - PENPOT_SMTP_TLS=true
```

I have tried different settings for `SMTP_DEFAULT_FROM` and `SMTP_DEFAULT_REPLY_TO`, like `Penpot <noreply@domain.com>` or just no value, but nothing works for version 1.18.1, while most options do work when I just change the version of the docker container.

The raw messages as reported by Postmark (with some sensitive information like domains changed)

Version 1.18.0:
```
From: noreply@domain.dev
Date: Wed, 05 Apr 2023 13:38:57 +0000
Subject: Invitation to join test_team
Message-Id: <577cc486-ee11-4699-91b2-60e1d5fd5c7b@mtasv.net>
Reply-To: noreply@domain.dev
To: user@domain.com
X-Penpot-Data: eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIn0.2TrWplxeLOmqIdlx1MUdPJHKOR1wdVWs1YJj7zCUM1yF9GSssetn4Q.QQnp5jwoOVRkCqPe.4ZqtgO79fCgYpM6Y-qLB-m4jpTRsc2SsmV7vUJK9kTT6c8CppneeN7XXRPAtZU5O48qf97q9wJmc_V2nH86mhzDJiKtDqo96A7KTGLlW6NRcTzp1m6D8Z618zBC3pnQ1PsDkFvQKRjlu_ei5tE-lFBFod4MknL_5hXKx0ir-2nNjy3h8A8qZqe0s1gawM88.JYlACdVjKnrUJ7R1b4kNJA
Feedback-ID: s9438387-_:s9438387:a178945:postmark
X-Complaints-To: abuse@postmarkapp.com
X-Job: 178945_9438387
X-PM-Message-Id: 577cc486-ee11-4699-91b2-60e1d5fd5c7b
X-PM-RCPT: |bTB8MTc4OTQ1fDk0MzgzODd8amVyb2VuQGludmVyc2FibGUuY29t|
X-PM-Message-Options: v1;1.s9IYTUlRmCZ7x_14cvy7-A.HZNCz3mW6MF-KJAypkmcKvZlH9gByV609ZnOFrMACfqEX0Br-H487E6l30tkfiukmQwbz0BnzfwvQwTk5P4myCG0ca9i-Vm675tV7XRIQ0c
X-dkim-options: s=20220907133241pm;d=domain.dev
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary=mk3-24c4309e5421452ebfc6c76b6c886845; charset=UTF-8

--mk3-24c4309e5421452ebfc6c76b6c886845
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hello!

pen pot has invited you to join the team =E2=80=9Ctest_team=E2=80=9D.

...etc.
```

Version 1.18.1

```
Received: from 1fc969a9558b (255-255-255-255.biz.domain.com [1.2.3.4])
	by p-pm-outbound03c-aws-euwest1c.smtpservice.postmarkapp.com (Postfix) with ESMTPSA id 9F2EC407DEF
	for <user@domain.com>; Wed,  5 Apr 2023 13:40:50 +0000 (UTC)
Date: Wed, 5 Apr 2023 13:40:50 +0000 (UTC)
Reply-To: noreply@domain.dev
To: user@domain.com
Message-ID: <528577623.2.1680702050399@domain.dev>
Subject: Invitation to join test_team
MIME-Version: 1.0
X-Penpot-Data: eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIn0.Z4jJlyCThEXa8Hv55Q-8vf0NS1QA_Nmow9YLh2wGkeiW4w-tCdvb3w.ksJsto57EZqaI4sp.tznkt5OFqCW_eKZMz0B6rFXuLjuO4yPxHE40pZ71PP52z7mNIsJ3BKJy1W_G4lgFHXGY2TxwyJ8FrVrJJil0Qsd5VCV-xDI_MrFT_YuUpBrIc08pOYAChZbmM-mToDaabONZ0LcmfRvF-vi7YKg0jYUwxknW7BVww2gQNQESgQ2NMoJ6orPXlp85LGNLtdI.AL5-Exhv4ZzhmsiNfMKNNQ
Content-Type: multipart/alternative; 
	boundary="----=_Part_1_1921548241.1680702050388"


------=_Part_1_1921548241.1680702050388
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Hello!

pen pot has invited you to join the team =E2=80=9Ctest_team=E2=80=9D.

...etc.
```

**Comment by niwinz** [comment]
Just to confirm, this regression happens on 1.18.1, and 1.18.0  (or 1.17.1) works ok?
strange because I'm not aware of any change on email part on the minor release, we need to recheck it.

**Comment by BlessedDisco** [comment]
I can confirm that I only get this issue on 1.18.1. Versions 1.18.0 and 1.17.1 work fine.

I find it strange too. I went through the code changes and did not see anything that is obviously related to the email-functionality as far as I could tell. I am not proficient in using clojure, so my analysis does not say too much ;).

I did test repeat the tests multiple times. I do not change any settings between tests except for the docker image versions.

---

On a sidenote. When I run the tests on the 1.18.0 version of the docker image, the backend logs show the version number 1.17.2:
```
I app.main - hint="welcome to penpot", flags="backend-api-doc,secure-session-cookies,backend-worker,login-with-oidc,smtp,email-verification", worker?=true, version="1.17.2-9408-g24fa4f71a"
```

Removing the docker images and downloading again did not change this behavior. So maybe the docker image of 1.18.0 does not contain the correct version of the code. Therefore, the email behavior might have been changed between 1.17.2 and 1.18.1 instead of between 1.18.0 and 1.18.1.

**Comment by BlessedDisco** [comment]
It seems that version 18 of penpot does not add the 'from' address in the mailheader.

An easy way to replicate the issue:

1. pull the `docker-compose.yaml` and run it as described in https://help.penpot.app/technical-guide/getting-started/#start-penpot
2. Go to penpot (`localhost:9001`), create a user, create a team and invite a random emailaddress to your team
3. Go to the mailcather running on `localhost:1080`
4. Select the received mail, go to 'source' and copy the mail
5. Bring down the docker containers
6. Edit `docker-compose.yaml`, to replace the `latest` tag with `1.17.2`
7. Bring the docker containers up again
8. Redo step 2-4

If you compare the mail sources, you get the following results:

*Version 1.17.2*
```
Date: Tue, 2 May 2023 08:38:57 +0000 (UTC)
From: no-reply@example.com
Reply-To: no-reply@example.com
To: test1@example.com
Message-ID: <1806883999.2.1683016737501@example.com>
Subject: Invitation to join test
...etc.
```

*Version 1.18.1 (latest)*
```
Date: Tue, 2 May 2023 08:32:22 +0000 (UTC)
Reply-To: no-reply@example.com
To: test1@example.com
Message-ID: <273795767.2.1683016342874@example.com>
Subject: Invitation to join test
...etc.
```

**Comment by BlessedDisco** [comment]
If I have to guess, the issue is in https://github.com/penpot/penpot/blob/1.18.1/backend/src/app/email.clj#L67

I don't know clojure, but the difference between `:keys [default-from]` (line 67) and `:keys [::default-reply-to] :as cfg` (line 74) stands out to me. If I see [the changes made between version 1.17.3 and 1.18.0](https://github.com/penpot/penpot/compare/1.17.3...1.18.0#diff-ba35a8678caea9d39cd8206c9d905ea3add0ba271b2446bc79d2bd85ba1e84ed), it seems logical to me that line 67 should have changed the same way that line 74 has been changed.

```clojure
(defn- assign-from
  [mmsg {:keys [default-from]} {:keys [from] :as props}]  ;; this line is different from
  (let [from (or from default-from)]
    (when from
      (let [from (parse-address from)]
        (.addFrom ^MimeMessage mmsg from)))))

(defn- assign-reply-to
  [mmsg {:keys [::default-reply-to] :as cfg} {:keys [reply-to] :as params}]  ;; this line
  (let [reply-to (or reply-to default-reply-to)]
    (when reply-to
      (let [reply-to (parse-address reply-to)]
        (.setReplyTo ^MimeMessage mmsg reply-to)))))
```

**Comment by niwinz** [comment]
You are right, thanks for looking on it. Honestly, I didn't have time for until now. I try to take a look on it tomorrow.

**Comment by firstsaofan** [comment]
I previously built version 1.17.1, which can be used normally. I deploy the latest version on the new server and configure STMP related configurations, but there will be errors. I have rolled back to version 1.17.1 and it is working normally. The error log is as follows:
```
[2023-05-06 14:34:25.988] E app.worker - hint="worker: unhandled exception on task"
SUMMARY:
 →  com.sun.mail.smtp.SMTPSendFailedException: 550 The "From" header is missing or invalid. Please follow RFC5322, RFC2047, RFC822 standard protocol. https://service.mail.qq.com/detail/124/995. (SMTPTransport.java:2374)
DETAIL:
 →  com.sun.mail.smtp.SMTPSendFailedException: 550 The "From" header is missing or invalid. Please follow RFC5322, RFC2047, RFC822 standard protocol. https://service.mail.qq.com/detail/124/995. (SMTPTransport.java:2374)
    at: com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2374)
        com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:2095)
        com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1301)
        app.email$eval31769$fn__31770$fn__31771$fn__31772.invoke(email.clj:312)
        app.email$eval31769$fn__31770$fn__31771.invoke(email.clj:306)
        app.email$eval31793$fn__31795$fn__31798.invoke(email.clj:326)
        app.worker$wrap_task_handler$fn__10919.invoke(worker.clj:83)
        app.worker$run_worker_loop_BANG_$handle_task__11563.invoke(worker.clj:394)
        app.worker$run_worker_loop_BANG_$run_task__11613.invoke(worker.clj:454)
        app.worker$run_worker_loop_BANG_$run_task_loop__11699.invoke(worker.clj:468)
        app.worker$run_worker_loop_BANG_.invokeStatic(worker.clj:485)
        app.worker$run_worker_loop_BANG_.invoke(worker.clj:344)
        app.worker$start_worker_BANG_$runnable_11415__11416.invoke(worker.clj:327)
        clojure.lang.AFn.run(AFn.java:22)
        java.lang.Thread.run(Thread.java:833)

```

**Comment by niwinz** [comment]
yep, this issue is already fixed, and will be available on 1.18.3 (which will be released soon, this week probably)

**Comment by L-WESLEY** [comment]
I also encountered a similar problem. The email function works normally with version 1.17.1 and 1.18.0, but cannot receive emails with version 1.18.1. I tested the latest version 1.18.3 and still cannot receive emails.

**Comment by niwinz** [comment]
I have tried the latest version  on a new /from scratch setup, and on localhost and it worked as expected.

**Comment by aronmal** [comment]
I am also still experiencing the bug after pulling updates for the compose stack.

Last line in the backend container log:
```
[2023-05-10 19:13:25.379] I app.email - 
```

**Comment by niwinz** [comment]
Can you provide more context?
What I want to say is that we have our SAAS and I have also done tests with the images of 1.8.3 (which is the same one that runs in our SAAS) and the sending of emails works. From what I deduce that what may be failing is some configuration change or something like that. But with the provided context I don't have a way to help.
