### ISSUE TITLE
bug:  Thumbnails not loading

### ISSUE THREAD

**Issue by Eschin** [uxbox/uxbox#3704]
### Steps To Reproduce

Steps to reproduce;
1. Login and view main Projects page with thumbnails.

### Expected behavior

Thumbnails display a preview image based on the underlying board's content.

### Actual behavior

Thumbnails never load, and all you see are 'spinning pencils'.

### Screenshots or video

![image](https://github.com/penpot/penpot/assets/5325383/54217a51-bbb4-4232-a4ad-2bc5f3541168)

### Desktop (please complete the following information)

- Win10
- Firefox 118.0.1 (64-bit)
- Chrome Version 118.0.5993.70

### Environment (please complete the following information)

- Penpot 1.19.3
- Docker version information;
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

-Docker compose file;
```
---
version: "3.5"

networks:
  penpot:

volumes:
  penpot_postgres_data:
  penpot_assets_data:

services:
  penpot-frontend:
    image: "penpotapp/frontend:latest"
    restart: unless-stopped
    ports:
      - 127.0.0.1:9001:80

    volumes:
      - penpot_assets_data:/opt/data

    env_file:
      - config.env

    depends_on:
      - penpot-backend
      - penpot-exporter

    networks:
      - penpot

  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: unless-stopped
    volumes:
      - penpot_assets_data:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    env_file:
      - config.env

    networks:
      - penpot

  penpot-exporter:
    image: "penpotapp/exporter:latest"
    restart: unless-stopped
    env_file:
      - config.env
    environment:
      # Don't touch it; this uses internal docker network to
      # communicate with the frontend.
      - PENPOT_PUBLIC_URI=http://penpot-frontend
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:13"
    restart: unless-stopped
    stop_signal: SIGINT

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - POSTGRES_USER=penpot
      - POSTGRES_PASSWORD=penpot

    volumes:
      - penpot_postgres_data:/var/lib/postgresql/data

    networks:
      - penpot

  penpot-redis:
    image: redis:6
    restart: unless-stopped
    networks:
      - penpot
```

### Additional context

Hello,

It's been a couple months since I've logged into my self-hosted penpot site, but upon doing so this morning, the thumbnails for all my projects seem broken. All I'm seeing is a 'spinning pencil' instead of the thumbnail itself.

Everything else appears to be working normally. If I go into a board, all assets/images show properly and functionality appears normal.

I've looked through the changelog(my systems are all auto-updated weekly, so an update may have knocked something askew), but I wasn't able to find anything that explains this issue.

Thanks for any help, and for making such an awesome tool. I've been very impressed with Penpot, and up until this minor issue, it's been working flawlessly :)

If any further information is needed, please let me know.

~Thanks!

**Comment by myfunnyandy** [comment]
Hi, thanks for the report! We'll track this issue [at taiga](https://tree.taiga.io/project/penpot/issue/6012) from here, this one is labeled as high priority so we hope to have it fixed soon.

**Comment by no6una9a** [comment]
Same situation here on my Penpot v1.19 docker instance!

**Comment by hongbo-code** [comment]
![image](https://github.com/penpot/penpot/assets/878648/2f0db454-2644-499f-8eee-949e7a03f9c0)
These are not displayable thumbnails Version 1.19

**Comment by bloemer** [comment]
Hi I noticed this too, but got it fixed with changing the public-uri value in
`penpot-backend:`
...
`   environment:`
...
`      - PENPOT_PUBLIC_URI=http://localhost:9001`
to 
`      - PENPOT_PUBLIC_URI=http://staged-domain:9001`

**Comment by Eschin** [comment]
> Hi I noticed this too, but got it fixed with changing the public-uri value in `penpot-backend:` ... ` - PENPOT_PUBLIC_URI=http://localhost:9001` to ` - PENPOT_PUBLIC_URI=http://staged-domain:9001`

Unfortunately, this didn't work for me 😞 

It appears there's been a fix staged for an upcoming release though. Been waiting for that to see if it ultimately resolves the issue.

**Comment by bloemer** [comment]
It wasn't active directly. Maybe some cache must be refreshed.

These changes had to be done in the docker-compser.yaml. I updated my comment with the missing `environment:` as super category.

Do you have some issues with the rendering of the board's content when zooming in and out, too? 
I had some, but this change also fixed that (I assume).

**Comment by bdelphin** [comment]
@bloemer solution fixed the problem for me aswell.

In my case, my penpot instance is running behind a reverse proxy, so my `docker-compose.yaml` looks like that : 

```yaml
  penpot-backend:
    ## ...
    environment:
      ## ...
      - PENPOT_PUBLIC_URI=https://penpot.my.domain
```

Don't forget to restart the containers : 

```
docker compose down
docker compose -p penpot -f docker-compose.yaml up -d
```

**Comment by Eschin** [comment]
Hmmm, wonder what's different about your setups 🤔 

I tried it a second time, and still no luck. My docker-compose `penpot-backend:` block after last attempt;

```
  penpot-backend:
    image: "penpotapp/backend:latest"
    restart: unless-stopped
    volumes:
      - penpot_assets_data:/opt/data

    depends_on:
      - penpot-postgres
      - penpot-redis

    env_file:
      - config.env
   
    environment:
      - PENPOT_PUBLIC_URI=https://penpot.my.domain
    networks:
      - penpot
```
I did change penpot.my.domain locally to match my actual domain. I know some folks can overlook that 😆 But yeah, no luck. Still no thumbnails in project preview. Just spinning pencils.
