### ISSUE TITLE
bug: Import of exported files fails

### ISSUE THREAD

**Issue by georgkrause** [uxbox/uxbox#3905]
### Steps To Reproduce

We have a pretty big draft hosted on our own Penpot. For some review I wanted to provide the file to an external reviewer, who tried to import the file in Hosted Penpot. It fails.

So the steps are basically: 
- Export a file (tried all three options) on self hosted Penpot
- Import in Hosted Penpot

### Expected behavior

The project gets imported

### Actual behavior

Nothing happens.

There is a log message in the Browser Console:

``` 
ERR [app.worker.import] hint="unexpected error on import process", project-id=#uuid "75aa5258-9a82-8002-8003-9171f7102343"
```

**Comment by madalenapmelo-kp** [comment]
Hi @georgkrause,

Could you please confirm if you are still experiencing this issue as of the latest version?

**Comment by georgkrause** [comment]
I am still unable to import any file from our self hosted penpot. 

Also, I think the handling of this issue is problematic. There wasn't any reaction to my report for 10 months, and you could have tried to reproduce the issue internally. And now the issue got closed because I didn't replied within a few weeks. :(

**Comment by madalenapmelo-kp** [comment]
Hi @georgkrause,

I completely understand, and please accept my apologies for the delay in getting back to you on this issue! We are a small team and at times it can be difficult to prioritize certain issues while continuing to develop Penpot into a tool that matches our users needs, but I can assure that we are actively trying to learn and improve :)

Regarding your issue, in order to look further into this, could you please confirm that you have the latest version of Penpot in your local installation?

**Comment by georgkrause** [comment]
@madalenapmelo-kp I do understand, sorry for complaining!

Sadly the situation changed and I am not managing the instance in question anymore and I don't seem to be able to see the running version as normal user? Am I missing something?

Anyways, the error message when importing a file isn't really helpful, so maybe thats something to work on?

![screenshot](https://github.com/user-attachments/assets/1a637b37-8294-4315-9a56-6ce30ecb9036)

**Comment by madalenapmelo-kp** [comment]
@georgkrause no problem at all :slightly_smiling_face:

We just released version 2.3 of Penpot so if you are using the latest version, you should see the release notes on the UI. Besides the version, if you are using custom values for the config flags that might be the issue as well, though we would need to check the config file in order to look further into this

**Comment by georgkrause** [comment]
@madalenapmelo-kp The instance in question is running 1.19.3. Since the next update to make is a major one, the operators don't want to do this between the usual work asks, which I understand.

Considering I am not actively using penpot anymore at the moment and I am unable to fully verify the issue is still existent, I think we can close this for now.

Sorry I wasn't able to properly provide the required information to track this down.

**Comment by madalenapmelo-kp** [comment]
@georgkrause thank you for letting me know! I'll close this issue then, but if you continue to experience it after the instance has been upgraded please feel free open a new one so that we can look further into this!
